data <- read.table(file="data/household_power_consumption.txt", header=TRUE, sep=";", dec=".", stringsAsFactors = FALSE)
FebData <- subset(data, Date=="1/2/2007" | Date=="2/2/2007")
GlobalActivePower <- as.numeric(FebData$Global_active_power)
png("plot1.png", width=480, height=480)
hist(GlobalActivePower, xlab="Global Active Power (kilowatts)", col="red", main="Global Active Power")
dev.off()